// Users
const AUTH_USER = 'AUTH_USER';
const AUTH_USER_ACTION = {
  type: AUTH_USER,
  uid: null
};

const UNAUTH_USER = 'UNAUTH_USER';
const UNAUTH_USER_ACTION = {
  type: UNAUTH_USER,
  uid: null
};

const FETCHING_USER = 'FETCHING_USER';
const FETCHING_USER_ACTION = {
  type: FETCHING_USER,
};

const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';
const FETCHING_USER_FAILURE_ACTION = {
  error: FETCHING_USER_FAILURE,
};

const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
const FETCHING_USER_SUCCESS_ACTION = {
  type: FETCHING_USER_SUCCESS,
  uid: null,
  user: null,
  timestamp: null,
};


//Ducks
const FETCHING_DUCK = 'FETCHING_DUCK';
const FETCHING_DUCK_ACTION = {
  type: FETCHING_DUCK
};

const FETCHING_DUCK_FAILURE = 'FETCHING_DUCK_FAILURE';
const FETCHING_DUCK_FAILURE_ACTION = {
  error: FETCHING_DUCK_FAILURE,
};

const REMOVE_FETCHING = 'REMOVE_FETCHING';
const REMOVE_FETCHING_ACTION = {
  type: REMOVE_FETCHING
};

const ADD_DUCK = 'ADD_DUCK';
const ADD_DUCK_ACTION = {
  type: ADD_DUCK,
  duck: null
};

const ADD_MULTIPLE_DUCKS = 'ADD_MULTIPLE_DUCKS';
const ADD_MULTIPLE_DUCKS_ACTION = {
  type: ADD_MULTIPLE_DUCKS,
  ducks: null,
};

// Feed
const SETTING_FEED_LISTENER = 'SETTING_FEED_LISTENER';
const SETTING_FEED_LISTENER_ACTION = {
  type: SETTING_FEED_LISTENER,

};

const FETCHING_FEED = 'FETCHING_FEED';
const FETCHING_FEED_ACTION = {
  type: FETCHING_FEED
};

const SETTING_FEED_LISTENER_FAILURE = 'FETCHING_FEED_FAILURE';
const SETTING_FEED_LISTENER_FAILURE_ACTION = {
  error: SETTING_FEED_LISTENER_FAILURE,
};

const SETTING_FEED_LISTENER_SUCCESS = 'SETTING_FEED_LISTENER_SUCCESS';
const SETTING_FEED_LISTENER_SUCCESS_ACTION = {
  type: SETTING_FEED_LISTENER_SUCCESS,
  duckIds: null,
};

const RESET_NEWS_DUCKS_AVAILABLE = 'RESET_NEWS_DUCKS_AVAILABLE';
const RESET_NEWS_DUCKS_AVAILABLE_ACTION = {
  type: RESET_NEWS_DUCKS_AVAILABLE,
};

// Listeners

const ADD_LISTENER = 'ADD_LISTENER';
const ADD_LISTENER_ACTION = {
  type: ADD_LISTENER,
  listenerId: null
};


// MODAL
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_MODAL_ACTION = {
  type: OPEN_MODAL,
};

const CLOSE_MODAL = 'CLOSE_MODAL';
const CLOSE_MODAL_ACTION = {
  type: CLOSE_MODAL,
};

const UPDATE_DUCK_TEXT = 'UPDATE_DUCK_TEXT';
const UPDATE_DUCK_TEXT_ACTION = {
  type: UPDATE_DUCK_TEXT,
  newDuckText: null,
};

//Replies
const FETCHING_REPLIES = 'FETCHING_REPLIES';
const FETCHING_REPLIES_ACTION = {
  type: FETCHING_REPLIES,
};

const FETCHING_REPLIES_ERROR = 'FETCHING_REPLIES_ERROR';
const FETCHING_REPLIES_ERROR_ACTION = {
  error: FETCHING_REPLIES_ERROR,
};

const FETCHING_REPLIES_SUCCESS = 'FETCHING_REPLIES_SUCCESS';
const FETCHING_REPLIES_SUCCESS_ACTION = {
  type: FETCHING_REPLIES_SUCCESS,
  replies: null,
  duckId: null,
  lastUpdate : Date.now(),
};


const ADD_REPLY = 'ADD_REPLY';
const ADD_REPLY_ACTION = {
  type: ADD_REPLY,
  duckId: null,
  reply: null,
};

const ADD_REPLY_ERROR = 'ADD_REPLY_ERROR';
const ADD_REPLY_ERROR_ACTION = {
  error: ADD_REPLY_ERROR,
};

const REMOVE_REPLY = 'REMOVE_REPLY';
const REMOVE_REPLY_ACTION = {
  type: REMOVE_REPLY,
  replyId: null,
};

const ADD_LIKE = 'ADD_LIKE';
const ADD_LIKE_ACTION = {
  type: ADD_LIKE,
};